// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfJR7UV-J_gZNxqAPpeMPZBSCOoxkHG2U',
    appId: '1:936849219887:web:8cb86494028c9f496e01da',
    messagingSenderId: '936849219887',
    projectId: 'fir-learn-39b8b',
    authDomain: 'fir-learn-39b8b.firebaseapp.com',
    storageBucket: 'fir-learn-39b8b.appspot.com',
    measurementId: 'G-06GM9HW939',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2ifnLNcjvezBmHEFgCu39V55U2ie2gsw',
    appId: '1:936849219887:android:252b4104bfaef4fa6e01da',
    messagingSenderId: '936849219887',
    projectId: 'fir-learn-39b8b',
    storageBucket: 'fir-learn-39b8b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRlmnL0zUAofmv1S4X9FXmHdvFK6R-dWA',
    appId: '1:936849219887:ios:439e045acfb293376e01da',
    messagingSenderId: '936849219887',
    projectId: 'fir-learn-39b8b',
    storageBucket: 'fir-learn-39b8b.appspot.com',
    iosClientId: '936849219887-klidmtje0i16ejcf7hehe69ubboho7pg.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseLearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRlmnL0zUAofmv1S4X9FXmHdvFK6R-dWA',
    appId: '1:936849219887:ios:439e045acfb293376e01da',
    messagingSenderId: '936849219887',
    projectId: 'fir-learn-39b8b',
    storageBucket: 'fir-learn-39b8b.appspot.com',
    iosClientId: '936849219887-klidmtje0i16ejcf7hehe69ubboho7pg.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseLearn',
  );
}
